import type { ShopGemstone } from '@/lib/services/shop/types';

const IMG = '/products/placeholder-gem.jpg';

const dim = (): ShopGemstone['dimensions'] => ({
  length: null,
  width: null,
  height: null,
});

/**
 * Minimaler Demo-Katalog nur für lokale Entwicklung, wenn PostgreSQL nicht erreichbar ist.
 * Keine Produktionsnutzung — echte Daten kommen aus der DB nach `docker compose up` + Seed.
 */
export function getDevCatalogFallbackGemstones(): ShopGemstone[] {
  return [
    {
      id: 'dev-fallback-sapphire-1',
      slug: 'demo-saphir-blau',
      name: 'Saphir (Demo)',
      category: 'Saphir',
      type: 'cut',
      price: 1280,
      currency: 'EUR',
      weight: 1.42,
      weightUnit: 'ct',
      origin: 'Sri Lanka',
      color: 'Blau',
      colorSaturation: 'Stark',
      clarity: 'VS',
      cut: 'Brillant',
      cutForm: 'Rund',
      treatment: 'Hitze',
      description: 'Beispielstein — Datenbank nicht erreichbar. Starten Sie Postgres und laden Sie echte Daten.',
      shortDescription: 'Demo für lokale Entwicklung',
      certification: null,
      rarity: null,
      dimensions: dim(),
      inStock: true,
      isSold: false,
      stock: 1,
      isNew: true,
      images: [IMG],
      videos: [],
    },
    {
      id: 'dev-fallback-ruby-1',
      slug: 'demo-rubin',
      name: 'Rubin (Demo)',
      category: 'Rubin',
      type: 'cut',
      price: 2450,
      currency: 'EUR',
      weight: 0.88,
      weightUnit: 'ct',
      origin: 'Myanmar',
      color: 'Rot',
      colorSaturation: 'Mittel',
      clarity: 'SI',
      cut: 'Oval',
      cutForm: 'Oval',
      treatment: 'Keine',
      description: 'Beispielstein für die Startseite „Neues“ und den Shop.',
      shortDescription: 'Demo Rubin',
      certification: null,
      rarity: null,
      dimensions: dim(),
      inStock: true,
      isSold: false,
      stock: 2,
      isNew: true,
      images: [IMG],
      videos: [],
    },
    {
      id: 'dev-fallback-emerald-1',
      slug: 'demo-smaragd',
      name: 'Smaragd (Demo)',
      category: 'Smaragd',
      type: 'cut',
      price: 1890,
      currency: 'EUR',
      weight: 1.05,
      weightUnit: 'ct',
      origin: 'Kolumbien',
      color: 'Grün',
      colorSaturation: 'Stark',
      clarity: 'VS',
      cut: 'Smaragd-Schliff',
      cutForm: 'Smaragd',
      treatment: 'Öl',
      description: 'Demo — mit echter DB erscheinen hier Ihre importierten Steine.',
      shortDescription: 'Demo Smaragd',
      certification: null,
      rarity: null,
      dimensions: dim(),
      inStock: true,
      isSold: false,
      stock: 1,
      isNew: true,
      images: [IMG],
      videos: [],
    },
    {
      id: 'dev-fallback-rough-1',
      slug: 'demo-rohstein',
      name: 'Rohedelstein-Mix (Demo)',
      category: 'Roh',
      type: 'rough',
      price: 320,
      currency: 'EUR',
      weight: 12.5,
      weightUnit: 'g',
      origin: 'Brasilien',
      color: null,
      colorSaturation: null,
      clarity: null,
      cut: null,
      cutForm: null,
      treatment: null,
      description: 'Demo-Rohmaterial.',
      shortDescription: 'Demo Roh',
      certification: null,
      rarity: null,
      dimensions: dim(),
      inStock: true,
      isSold: false,
      stock: 5,
      isNew: false,
      images: [IMG],
      videos: [],
    },
  ];
}
