// UN-Länderliste (alle 193 UN-Mitgliedsstaaten + Vatikanstadt)
export const UN_COUNTRIES = [
  'Afghanistan',
  'Ägypten',
  'Albanien',
  'Algerien',
  'Andorra',
  'Angola',
  'Antigua und Barbuda',
  'Äquatorialguinea',
  'Argentinien',
  'Armenien',
  'Aserbaidschan',
  'Äthiopien',
  'Australien',
  'Bahamas',
  'Bahrain',
  'Bangladesch',
  'Barbados',
  'Belarus',
  'Belgien',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivien',
  'Bosnien und Herzegowina',
  'Botswana',
  'Brasilien',
  'Brunei',
  'Bulgarien',
  'Burkina Faso',
  'Burundi',
  'Chile',
  'China',
  'Costa Rica',
  'Dänemark',
  'Deutschland',
  'Dominica',
  'Dominikanische Republik',
  'Dschibuti',
  'Ecuador',
  'El Salvador',
  'Elfenbeinküste',
  'Eritrea',
  'Estland',
  'Eswatini',
  'Fidschi',
  'Finnland',
  'Frankreich',
  'Gabun',
  'Gambia',
  'Georgien',
  'Ghana',
  'Grenada',
  'Griechenland',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Indien',
  'Indonesien',
  'Irak',
  'Iran',
  'Irland',
  'Island',
  'Israel',
  'Italien',
  'Jamaika',
  'Japan',
  'Jemen',
  'Jordanien',
  'Kambodscha',
  'Kamerun',
  'Kanada',
  'Kap Verde',
  'Kasachstan',
  'Katar',
  'Kenia',
  'Kirgisistan',
  'Kiribati',
  'Kolumbien',
  'Komoren',
  'Kongo',
  'Demokratische Republik Kongo',
  'Kroatien',
  'Kuba',
  'Kuwait',
  'Laos',
  'Lesotho',
  'Lettland',
  'Libanon',
  'Liberia',
  'Libyen',
  'Liechtenstein',
  'Litauen',
  'Luxemburg',
  'Madagaskar',
  'Malawi',
  'Malaysia',
  'Malediven',
  'Mali',
  'Malta',
  'Marokko',
  'Marshallinseln',
  'Mauretanien',
  'Mauritius',
  'Mexiko',
  'Mikronesien',
  'Moldau',
  'Monaco',
  'Mongolei',
  'Montenegro',
  'Mosambik',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Neuseeland',
  'Nicaragua',
  'Niederlande',
  'Niger',
  'Nigeria',
  'Nordkorea',
  'Nordmazedonien',
  'Norwegen',
  'Oman',
  'Österreich',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua-Neuguinea',
  'Paraguay',
  'Peru',
  'Philippinen',
  'Polen',
  'Portugal',
  'Ruanda',
  'Rumänien',
  'Russland',
  'Salomonen',
  'Sambia',
  'Samoa',
  'San Marino',
  'São Tomé und Príncipe',
  'Saudi-Arabien',
  'Schweden',
  'Schweiz',
  'Senegal',
  'Serbien',
  'Seychellen',
  'Sierra Leone',
  'Simbabwe',
  'Singapur',
  'Slowakei',
  'Slowenien',
  'Somalia',
  'Spanien',
  'Sri Lanka',
  'St. Kitts und Nevis',
  'St. Lucia',
  'St. Vincent und die Grenadinen',
  'Südafrika',
  'Sudan',
  'Südkorea',
  'Südsudan',
  'Suriname',
  'Syrien',
  'Tadschikistan',
  'Taiwan',
  'Tansania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad und Tobago',
  'Tschad',
  'Tschechien',
  'Tunesien',
  'Türkei',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'Ungarn',
  'Uruguay',
  'USA',
  'Usbekistan',
  'Vanuatu',
  'Vatikanstadt',
  'Venezuela',
  'Vereinigte Arabische Emirate',
  'Vietnam',
  'Weißrussland',
  'Zentralafrikanische Republik',
  'Zypern',
].sort();

// Qualitätsoptionen
export const QUALITY_OPTIONS = [
  'sehr gut',
  'gut',
  'zufriedenstellend',
  'ausreichend',
];

// Erweiterte Edelsteinfarben (100+ Farben alphabetisch)
export const GEMSTONE_COLORS = [
  'Achatgrau',
  'Aprikose',
  'Aquamarinblau',
  'Aschgrau',
  'Beige',
  'Bernstein',
  'Bisquit',
  'Blassblau',
  'Blassgelb',
  'Blassgrün',
  'Blasslila',
  'Blassrosa',
  'Blau',
  'Blau-Grün',
  'Blau-Violett',
  'Bläulich',
  'Bläulich-Grün',
  'Bläulich-Violett',
  'Braun',
  'Braun-Gelb',
  'Braun-Rot',
  'Bronze',
  'Champagner',
  'Chromgrün',
  'Cognac',
  'Cyan',
  'Dunkelblau',
  'Dunkelbraun',
  'Dunkelgelb',
  'Dunkelgrau',
  'Dunkelgrün',
  'Dunkellila',
  'Dunkelorange',
  'Dunkelrosa',
  'Dunkelrot',
  'Dunkeltürkis',
  'Dunkelviolett',
  'Eisblau',
  'Elfenbein',
  'Emeraldgrün',
  'Farblos',
  'Feuerrot',
  'Flieder',
  'Gelb',
  'Gelb-Grün',
  'Gelb-Orange',
  'Gelblich',
  'Gelblich-Grün',
  'Gold',
  'Goldgelb',
  'Grau',
  'Grau-Blau',
  'Grau-Grün',
  'Grün',
  'Grün-Blau',
  'Grün-Gelb',
  'Grünlich',
  'Grünlich-Blau',
  'Himmelblau',
  'Honiggelb',
  'Indigo',
  'Jadegrün',
  'Kamel',
  'Karminrot',
  'Kastanienbraun',
  'Kobaltblau',
  'Koralle',
  'Kupfer',
  'Lachs',
  'Lavendel',
  'Lemon',
  'Lila',
  'Lila-Blau',
  'Lila-Rot',
  'Magenta',
  'Mahagoni',
  'Marineblau',
  'Mint',
  'Moosgrün',
  'Navy',
  'Ocker',
  'Oliv',
  'Olivgrün',
  'Orange',
  'Orange-Gelb',
  'Orange-Rot',
  'Orchidee',
  'Pastellblau',
  'Pastellgelb',
  'Pastellgrün',
  'Pastelllila',
  'Pastellrosa',
  'Perlmutt',
  'Pfirsich',
  'Pink',
  'Pink-Rot',
  'Platin',
  'Purpur',
  'Rosa',
  'Rosa-Lila',
  'Rosa-Rot',
  'Rot',
  'Rot-Orange',
  'Rot-Violett',
  'Rötlich',
  'Rötlich-Orange',
  'Rötlich-Violett',
  'Rubinrot',
  'Safrangelb',
  'Salmon',
  'Scharlachrot',
  'Schwarz',
  'Schwarz-Blau',
  'Schwarz-Grün',
  'Schwarz-Rot',
  'Schwarz-Violett',
  'Silber',
  'Smaragdgrün',
  'Tannengrün',
  'Taupe',
  'Teal',
  'Tiefblau',
  'Tiefgrün',
  'Tiefrot',
  'Tiefviolett',
  'Türkis',
  'Türkis-Blau',
  'Türkis-Grün',
  'Ultramarin',
  'Vanille',
  'Violett',
  'Violett-Blau',
  'Violett-Rot',
  'Violettlich',
  'Weiß',
  'Weiß-Gelb',
  'Weiß-Grün',
  'Weißlich',
  'Weißlich-Blau',
  'Weißlich-Grün',
  'Zitronengelb',
  'Zitronengrün',
].sort();

// Schliffarten (Schliff → Schliffart)
export const CUT_STYLE_OPTIONS = [
  'Brillant-Schliff',
  'Stufen-Schliff',
  'Konkav-Schliff',
  'Portugiesischer Schliff',
  'Treppen-Schliff',
  'Rosen-Schliff',
  'Schachbrett-Schliff',
  'Mischschliff',
  'Cabochon',
];

// Erweiterte Edelstein-Kategorien (50+ zusätzliche Steine)
export const GEMSTONE_CATEGORIES = [
  'Achat',
  'Alexandrit',
  'Amethyst',
  'Apatit',
  'Aquamarin',
  'Aventurin',
  'Beryll',
  'Beryllonit',
  'Brasilianit',
  'Calcit',
  'Chalcedon',
  'Chrysoberyll',
  'Chrysopras',
  'Citrin',
  'Danburit',
  'Demantoid',
  'Diamant',
  'Diopsid',
  'Epidot',
  'Fluorit',
  'Garnet',
  'Goshenit',
  'Grossular',
  'Hämatit',
  'Heliodor',
  'Hessonit',
  'Hiddenit',
  'Iolith',
  'Jade',
  'Jaspis',
  'Korund',
  'Kunzit',
  'Labradorit',
  'Lapis Lazuli',
  'Moldavit',
  'Mondstein',
  'Morganit',
  'Obsidian',
  'Opal',
  'Padparadscha',
  'Peridot',
  'Prehnit',
  'Pyrit',
  'Quarz',
  'Rhodolith',
  'Rubin',
  'Saphir',
  'Sardonyx',
  'Schörl',
  'Smaragd',
  'Spessartin',
  'Spinell',
  'Spodumen',
  'Sunstone',
  'Tansanit',
  'Tigerauge',
  'Topas',
  'Tourmalin',
  'Tsavorit',
  'Turmalin',
  'Uvarovit',
  'Vesuvianit',
  'Zirkon',
  'Zoisit',
].sort();

// Schliffformen (Smaragd bereits vorhanden, aber sicherstellen)
export const CUT_FORM_OPTIONS = [
  'Rund',
  'Oval',
  'Kissen',
  'Herz',
  'Tropfen',
  'Marquise',
  'Princess',
  'Brillant',
  'Smaragd',
  'Baguette',
  'Asscher',
  'Trillion',
].sort();

// Entstehung (Imitation hinzufügen, behandelt entfernen)
export const ORIGIN_TYPE_OPTIONS = [
  'natürlich',
  'synthetisch',
  'Imitation',
];

// Reinheitsgrade (vereinfacht mit Erläuterungen)
export const CLARITY_OPTIONS = [
  { value: 'FL', label: 'FL - Flawless (Lupenrein, keine Einschlüsse)' },
  { value: 'VVS', label: 'VVS - Very Very Slightly Included (Sehr, sehr kleine Einschlüsse, nur unter 10-facher Vergrößerung erkennbar)' },
  { value: 'VS', label: 'VS - Very Slightly Included (Sehr kleine Einschlüsse, unter 10-facher Vergrößerung erkennbar, nicht mit bloßem Auge)' },
  { value: 'SI', label: 'SI - Slightly Included (Kleine Einschlüsse, unter 10-facher Vergrößerung leicht erkennbar, manchmal mit bloßem Auge sichtbar)' },
  { value: 'I', label: 'I - Included (Einschlüsse mit bloßem Auge deutlich sichtbar, können Brillanz beeinträchtigen)' },
];

