// UN-Länderliste (alle 193 UN-Mitgliedsstaaten + Vatikanstadt)
const UN_COUNTRIES_ARRAY = [
  'Afghanistan',
  'Ägypten',
  'Albanien',
  'Algerien',
  'Andorra',
  'Angola',
  'Antigua und Barbuda',
  'Äquatorialguinea',
  'Argentinien',
  'Armenien',
  'Aserbaidschan',
  'Äthiopien',
  'Australien',
  'Bahamas',
  'Bahrain',
  'Bangladesch',
  'Barbados',
  'Belarus',
  'Belgien',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivien',
  'Bosnien und Herzegowina',
  'Botswana',
  'Brasilien',
  'Brunei',
  'Bulgarien',
  'Burkina Faso',
  'Burundi',
  'Chile',
  'China',
  'Costa Rica',
  'Dänemark',
  'Deutschland',
  'Dominica',
  'Dominikanische Republik',
  'Dschibuti',
  'Ecuador',
  'El Salvador',
  'Elfenbeinküste',
  'Eritrea',
  'Estland',
  'Eswatini',
  'Fidschi',
  'Finnland',
  'Frankreich',
  'Gabun',
  'Gambia',
  'Georgien',
  'Ghana',
  'Grenada',
  'Griechenland',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Indien',
  'Indonesien',
  'Irak',
  'Iran',
  'Irland',
  'Island',
  'Israel',
  'Italien',
  'Jamaika',
  'Japan',
  'Jemen',
  'Jordanien',
  'Kambodscha',
  'Kamerun',
  'Kanada',
  'Kap Verde',
  'Kasachstan',
  'Katar',
  'Kenia',
  'Kirgisistan',
  'Kiribati',
  'Kolumbien',
  'Komoren',
  'Kongo',
  'Demokratische Republik Kongo',
  'Kroatien',
  'Kuba',
  'Kuwait',
  'Laos',
  'Lesotho',
  'Lettland',
  'Libanon',
  'Liberia',
  'Libyen',
  'Liechtenstein',
  'Litauen',
  'Luxemburg',
  'Madagaskar',
  'Malawi',
  'Malaysia',
  'Malediven',
  'Mali',
  'Malta',
  'Marokko',
  'Marshallinseln',
  'Mauretanien',
  'Mauritius',
  'Mexiko',
  'Mikronesien',
  'Moldau',
  'Monaco',
  'Mongolei',
  'Montenegro',
  'Mosambik',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Neuseeland',
  'Nicaragua',
  'Niederlande',
  'Niger',
  'Nigeria',
  'Nordkorea',
  'Nordmazedonien',
  'Norwegen',
  'Oman',
  'Österreich',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua-Neuguinea',
  'Paraguay',
  'Peru',
  'Philippinen',
  'Polen',
  'Portugal',
  'Ruanda',
  'Rumänien',
  'Russland',
  'Salomonen',
  'Sambia',
  'Samoa',
  'San Marino',
  'São Tomé und Príncipe',
  'Saudi-Arabien',
  'Schweden',
  'Schweiz',
  'Senegal',
  'Serbien',
  'Seychellen',
  'Sierra Leone',
  'Simbabwe',
  'Singapur',
  'Slowakei',
  'Slowenien',
  'Somalia',
  'Spanien',
  'Sri Lanka',
  'St. Kitts und Nevis',
  'St. Lucia',
  'St. Vincent und die Grenadinen',
  'Südafrika',
  'Sudan',
  'Südkorea',
  'Südsudan',
  'Suriname',
  'Syrien',
  'Tadschikistan',
  'Taiwan',
  'Tansania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad und Tobago',
  'Tschad',
  'Tschechien',
  'Tunesien',
  'Türkei',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'Ungarn',
  'Uruguay',
  'USA',
  'Usbekistan',
  'Vanuatu',
  'Vatikanstadt',
  'Venezuela',
  'Vereinigte Arabische Emirate',
  'Vietnam',
  'Weißrussland',
  'Zentralafrikanische Republik',
  'Zypern',
];

export const UN_COUNTRIES = [...UN_COUNTRIES_ARRAY].sort();

// Qualitätsoptionen
export const QUALITY_OPTIONS = [
  'sehr gut',
  'gut',
  'zufriedenstellend',
  'ausreichend',
];

// Erweiterte Edelsteinfarben (100+ Farben alphabetisch)
const GEMSTONE_COLORS_ARRAY = [
  'Achatgrau',
  'Aprikose',
  'Aquamarinblau',
  'Aschgrau',
  'Beige',
  'Bernstein',
  'Bisquit',
  'Blassblau',
  'Blassgelb',
  'Blassgrün',
  'Blasslila',
  'Blassrosa',
  'Blau',
  'Blau-Grün',
  'Blau-Violett',
  'Bläulich',
  'Bläulich-Grün',
  'Bläulich-Violett',
  'Braun',
  'Braun-Gelb',
  'Braun-Rot',
  'Bronze',
  'Champagner',
  'Chromgrün',
  'Cognac',
  'Cyan',
  'Dunkelblau',
  'Dunkelbraun',
  'Dunkelgelb',
  'Dunkelgrau',
  'Dunkelgrün',
  'Dunkellila',
  'Dunkelorange',
  'Dunkelrosa',
  'Dunkelrot',
  'Dunkeltürkis',
  'Dunkelviolett',
  'Eisblau',
  'Elfenbein',
  'Emeraldgrün',
  'Farblos',
  'Feuerrot',
  'Flieder',
  'Gelb',
  'Gelb-Grün',
  'Gelb-Orange',
  'Gelblich',
  'Gelblich-Grün',
  'Gold',
  'Goldgelb',
  'Grau',
  'Grau-Blau',
  'Grau-Grün',
  'Grün',
  'Grün-Blau',
  'Grün-Gelb',
  'Grünlich',
  'Grünlich-Blau',
  'Himmelblau',
  'Honiggelb',
  'Indigo',
  'Jadegrün',
  'Kamel',
  'Karminrot',
  'Kastanienbraun',
  'Kobaltblau',
  'Koralle',
  'Kupfer',
  'Lachs',
  'Lavendel',
  'Lemon',
  'Lila',
  'Lila-Blau',
  'Lila-Rot',
  'Magenta',
  'Mahagoni',
  'Marineblau',
  'Mint',
  'Moosgrün',
  'Navy',
  'Ocker',
  'Oliv',
  'Olivgrün',
  'Orange',
  'Orange-Gelb',
  'Orange-Rot',
  'Orchidee',
  'Pastellblau',
  'Pastellgelb',
  'Pastellgrün',
  'Pastelllila',
  'Pastellrosa',
  'Perlmutt',
  'Pfirsich',
  'Pink',
  'Pink-Rot',
  'Platin',
  'Purpur',
  'Rosa',
  'Rosa-Lila',
  'Rosa-Rot',
  'Rot',
  'Rot-Orange',
  'Rot-Violett',
  'Rötlich',
  'Rötlich-Orange',
  'Rötlich-Violett',
  'Rubinrot',
  'Safrangelb',
  'Salmon',
  'Scharlachrot',
  'Schwarz',
  'Schwarz-Blau',
  'Schwarz-Grün',
  'Schwarz-Rot',
  'Schwarz-Violett',
  'Silber',
  'Smaragdgrün',
  'Tannengrün',
  'Taupe',
  'Teal',
  'Tiefblau',
  'Tiefgrün',
  'Tiefrot',
  'Tiefviolett',
  'Türkis',
  'Türkis-Blau',
  'Türkis-Grün',
  'Ultramarin',
  'Vanille',
  'Violett',
  'Violett-Blau',
  'Violett-Rot',
  'Violettlich',
  'Weiß',
  'Weiß-Gelb',
  'Weiß-Grün',
  'Weißlich',
  'Weißlich-Blau',
  'Weißlich-Grün',
  'Zitronengelb',
  'Zitronengrün',
];

export const GEMSTONE_COLORS = [...GEMSTONE_COLORS_ARRAY].sort();

// Schliffarten (Schliff → Schliffart)
export const CUT_STYLE_OPTIONS = [
  'Brillant-Schliff',
  'Stufen-Schliff',
  'Konkav-Schliff',
  'Portugiesischer Schliff',
  'Treppen-Schliff',
  'Rosen-Schliff',
  'Schachbrett-Schliff',
  'Mischschliff',
  'Cabochon',
];

// Erweiterte Edelstein-Kategorien (150+ Schmucksteine)
const GEMSTONE_CATEGORIES_ARRAY = [
  'Achat',
  'Albit',
  'Alexandrit',
  'Amazonit',
  'Amethyst',
  'Andalusit',
  'Andradit',
  'Apatit',
  'Aquamarin',
  'Aventurin',
  'Azurit',
  'Benitoit',
  'Beryll',
  'Beryllonit',
  'Bixbit',
  'Brasilianit',
  'Calcit',
  'Carnelian',
  'Cerussit',
  'Chalcedon',
  'Charoit',
  'Chrysoberyll',
  'Chrysokoll',
  'Chrysopras',
  'Citrin',
  'Cordierit',
  'Danburit',
  'Demantoid',
  'Diamant',
  'Diopsid',
  'Dumortierit',
  'Ekanit',
  'Epidot',
  'Eudialyt',
  'Fenakit',
  'Fluorit',
  'Garnet',
  'Goshenit',
  'Grossular',
  'Hämatit',
  'Hambergit',
  'Heliodor',
  'Hessonit',
  'Hiddenit',
  'Howlith',
  'Hypersthen',
  'Iolith',
  'Jade',
  'Jadeit',
  'Jaspis',
  'Jeremejewit',
  'Korund',
  'Kunzit',
  'Kyanit',
  'Labradorit',
  'Lapis Lazuli',
  'Larimar',
  'Lazulith',
  'Lepidolith',
  'Magnetit',
  'Malachit',
  'Moldavit',
  'Mondstein',
  'Morganit',
  'Obsidian',
  'Opal',
  'Padparadscha',
  'Peridot',
  'Perowskit',
  'Phenakit',
  'Prehnit',
  'Pyrit',
  'Pyrop',
  'Quarz',
  'Rhodochrosit',
  'Rhodolith',
  'Rhodonit',
  'Rubin',
  'Rutil',
  'Saphir',
  'Sardonyx',
  'Schörl',
  'Selenit',
  'Serpentin',
  'Smaragd',
  'Smithsonit',
  'Spessartin',
  'Spinell',
  'Spodumen',
  'Staurolith',
  'Sunstone',
  'Tansanit',
  'Tanzanit',
  'Tigerauge',
  'Topas',
  'Tourmalin',
  'Tsavorit',
  'Turmalin',
  'Türkis',
  'Uvarovit',
  'Variscit',
  'Vesuvianit',
  'Zirkon',
  'Zoisit',
  'Zultanit',
];

export const GEMSTONE_CATEGORIES = [...GEMSTONE_CATEGORIES_ARRAY].sort();

// Schliffformen (Smaragd bereits vorhanden, aber sicherstellen)
const CUT_FORM_OPTIONS_ARRAY = [
  'Rund',
  'Oval',
  'Kissen',
  'Herz',
  'Tropfen',
  'Marquise',
  'Princess',
  'Brillant',
  'Smaragd',
  'Baguette',
  'Asscher',
  'Trillion',
];

export const CUT_FORM_OPTIONS = [...CUT_FORM_OPTIONS_ARRAY].sort();

// Entstehung (Imitation hinzufügen, behandelt entfernen)
export const ORIGIN_TYPE_OPTIONS = [
  'natürlich',
  'synthetisch',
  'Imitation',
];

// Reinheitsgrade (vereinfacht mit Erläuterungen)
export const CLARITY_OPTIONS = [
  { value: 'FL', label: 'FL - Flawless (Lupenrein, keine Einschlüsse)' },
  { value: 'VVS', label: 'VVS - Very Very Slightly Included (Sehr, sehr kleine Einschlüsse, nur unter 10-facher Vergrößerung erkennbar)' },
  { value: 'VS', label: 'VS - Very Slightly Included (Sehr kleine Einschlüsse, unter 10-facher Vergrößerung erkennbar, nicht mit bloßem Auge)' },
  { value: 'SI', label: 'SI - Slightly Included (Kleine Einschlüsse, unter 10-facher Vergrößerung leicht erkennbar, manchmal mit bloßem Auge sichtbar)' },
  { value: 'I', label: 'I - Included (Einschlüsse mit bloßem Auge deutlich sichtbar, können Brillanz beeinträchtigen)' },
];
